= README

== Setup Instructions

=== Create the Server

Spin the droplet using vagrant. Make sure to define these secrets in
`secrets/digitalocean.env`:

    DO_DROPLET_NAME=jupyterhub-workshop
    DO_SSH_KEY_NAME=<ssh key nickname in digital ocean>
    DO_SSH_PRIVATE_KEY=<path to ssh private key set-up with digital ocean>
    DO_TOKEN=<digital ocean token>
    # digital ocean region names like: nyc3, lon1, etc.
    DO_REGION=fra1
    # for setup, 4 CPU and 8GiB of RAM is nice, scale down after
    DO_SIZE=c-4

To spin the droplet:

    vagrant up

=== Setup on the Server

Connect

    vagrant ssh

Last few things

    apt install make
    cd /vagrant/
    make

If you are using a custom notebook (it is what's by default here, see `.env` for name), you need to build it and rebuild notebook_image:

  cd examples/custom-notebook-server/
  # <change what you need or use another example>
  docker build -t workshop-notebook .
  cd ../../
  make notebook_image
  make build

=== Setup GitHub's OAuth

Follow the instructions under the *Authenticator setup* section of `README.upstream.md` file.

Our GitHub OAuth should be done under here: https://github.com/organizations/GoSecure/settings/applications/

By default our setup is open to anyone to create an account like for an open
workshop with no pre-registrations (different options available below). Setup
the users with admin privileges in advance by writing the github usernames to
the `secrets/admins` file (one per line).


=== Add TLS Certificates with Lets Encrypt

* install certbot

    apt install certbot

* create certs using certbot and its temp webserver (make sure docker-compose
  is shut down before)

    certbot certonly --standalone -d <domain-name>
    cp /etc/letsencrypt/live/<domain-name>/fullchain.pem secrets/jupyterhub.crt
    cp /etc/letsencrypt/live/<domain-name>/privkey.pem secrets/jupyterhub.key

* Rebuild docker-compose with updated secrets and certs

    make

Everything should work:

    docker-compose up

== Optional: Only allow specific users

If you create a `secrets/users` file with a list of allowed GitHub usernames,
only these usernames will be able to sign-up to the server.

When you change that list, you need to restart the JupyterHub container.
Easiest way to achieve this is to kill the docker-compose environment, 
run `make` and restart docker-compose.

    <ctrl-d>
    make
    docker-compose up

User lists can optionally have an `admin` tag to identify admin users. Ex:

    linus admin
    obilodeau
    masarah admin


== Optional: Stop Open Registrations

// TODO


== Optional: User Instances Exposed to the Internet

// TODO


== Special Workshop Files Overlay

.Read-only shared with all participants

All users will have access to a directory in their own homes (`/home/jovyan/`)
called `workshop/` that will be mapped to the servers' `/srv/workshop/` via a
docker volume.

Changes made there will be reflected instantly.


.Files for participants (writable and executable)

On container creation, a directory called `labs/` will be created and
populated from the servers' `/srv/workshop/labs-source/`.

This will happen only once per user. If you need to re-populate it, you need
to delete the user' files in his volume. These are visible under:
`/var/lib/docker/volumes/jupyterhub-user-<username>/_data/`
