= README

== Setup Instructions

=== Prepare for Deployment

These steps should be done locally before provisioning the JupterHub
server to facilitate deployment.

==== Setup GitHub Authentication

Create a GitHub application reflecting the purpose of your JupyterHub
workshop. It will be used to allow users to login and gain access to
the workshop servers. You should know the following information ahead
of time:

* Workshop Name (Application Name)
* Workshop Server URL (Doesn't need to resolve yet)
* Workshop Description
* Workshop Icon if desired.

Follow the instructions under the *Authenticator setup* section of
`README.upstream.md` and create `secrets/oauth.env` with the following
content:

  GITHUB_CLIENT_ID=<github_client_id>
  GITHUB_CLIENT_SECRET=<github_client_secret>
  OAUTH_CALLBACK_URL=https://<myhost.mydomain>/hub/oauth_callback

*NOTE*: Applications for workshops should be created under the GoSecure organization at
https://github.com/organizations/GoSecure/settings/applications/new

Ask organisation admin to create the application with the required information.

By default our setup is open to anyone to create an account like for an open
workshop with no pre-registrations (different options available below). Setup
the users with admin privileges in advance by writing the github usernames to
the `secrets/admins` file (one per line).

==== Setup Administrator Accounts

Add one or more accounts in `secrets/admins`. These accounts will be
granted full access to the Jupyter Notebook.


==== Workshop Files: Overlay Filesystem

There are two ways to expose files to the workshop attendees.

.Read-only shared with all participants

All users will have access to a directory in their own homes (`/home/jovyan/`)
called `workshop/` that will be mapped to the servers' `/srv/workshop/` via a
docker volume.

Changes made in `/srv/workshop/*` will be reflected instantly for all participants.


.Files for participants (writable and executable)

On container creation, a directory called `labs/` will be created and
populated from the servers' `/srv/workshop/labs-source/` content.

This will happen only once per user. If you need to re-populate it, you need
to delete the user' files in his volume. These are visible under:
`/var/lib/docker/volumes/jupyterhub-user-<username>/_data/`

=== Create the Server

Ensure that you have the Digital Ocean provider installed:

    vagrant plugin install vagrant-digitalocean

Configure your Digital Ocean credentials in `secrets/digitalocean.env`:

    DO_DROPLET_NAME=jupyterhub-workshop
    DO_SSH_KEY_NAME=<ssh key nickname in digital ocean>
    DO_SSH_PRIVATE_KEY=<path to ssh private key set-up with digital ocean>
    DO_TOKEN=<digital ocean token>
    # digital ocean region names like: nyc3, lon1, etc.
    DO_REGION=fra1
    # for setup, 4 CPU and 8GiB of RAM is nice, scale down after
    DO_SIZE=c-4

Spawn and provision the droplet. It might take a while to setup and
provision, so be patient. The repository should be synchronized to
`/vagrant`

    vagrant up

=== Server-Side Configuration

To connect to the server via SSH, run:

    vagrant ssh

*NOTE*: If you are having trouble with the following error:

    The private key you're attempting to use with this Vagrant box uses
    an unsupported encryption type. The SSH library Vagrant uses does not support
    this key type. Please use `ssh-rsa` or `ssh-dss` instead. Note that
    sometimes keys in your ssh-agent can interfere with this as well,
    so verify the keys are valid there in addition to standard
    file paths.

Then you need to install the following gems on your local workstation
in order to support ed25519 private keys for SSH:

    sudo gem install rbnacl --no-user-install -i /opt/vagrant/embedded/gems;
    sudo gem install bcrypt_pbkdf --no-user-install -i /opt/vagrant/embedded/gems;
    sudo gem install rbnacl-libsodium --no-user-install -i /opt/vagrant/embedded/gems;
    sudo gem install ed25519 --no-user-install -i /opt/vagrant/embedded/gems;

See https://github.com/hashicorp/vagrant/issues/4367 for more dtails.

==== Build Notebook Image

If you are using a custom notebook (it is what's by default here, see `.env` for name), you need to build it and rebuild notebook_image:

  cd examples/custom-notebook-server/
  # <change what you need or use another example>
  docker build -t workshop-notebook .
  cd ../../
  make notebook_image

==== Configure TLS and HTTPS with Certbot

* Ensure that your domain name resolves to the created droplet public address.
* create certs using certbot and its temp webserver (make sure docker-compose
  is shut down before)

    certbot certonly --standalone -d <domain-name>
    cp /etc/letsencrypt/live/<domain-name>/fullchain.pem secrets/jupyterhub.crt
    cp /etc/letsencrypt/live/<domain-name>/privkey.pem secrets/jupyterhub.key


==== Launch the Notebook Server

After everything is configured, you can spawn the notebook server with the following commands:

      cd /vagrant
      make
      docker-compose up

Whenever changing the secrets or environment variables, rebuiding and
relaunching the images is required:

    docker-compose down
    make
    docker-compose up

== Optional: Only allow specific users

If you create a `secrets/users` file with a list of allowed GitHub usernames,
only these usernames will be able to sign-up to the server.

When you change that list, you need to restart the JupyterHub container.
Easiest way to achieve this is to kill the docker-compose environment, 
run `make` and restart docker-compose.

    <ctrl-d>
    make
    docker-compose up

User lists can optionally have an `admin` tag to identify admin users. Ex:

    linus admin
    obilodeau
    masarah admin


== Optional: Stop Open Registrations

// TODO


== Optional: User Instances Exposed to the Internet

Uncomment the following line in the `.env` file and make sure to rebuild the
`hub` container.

    DOCKER_NOTEBOOK_EXPOSE_NETWORK=true


